# Generated by Django 5.2.16 on 2026-07-23 14:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("organisation_profile", "Organisation Profile"),
                            ("business_activities", "Business Activities"),
                            ("products_services", "Products & Services"),
                            ("locations", "Locations"),
                            ("departments", "Departments"),
                            ("people_roles", "People & Roles"),
                            ("processes", "Processes"),
                            ("information", "Information"),
                            ("personal_information", "Personal Information"),
                            ("systems", "Systems"),
                            ("applications", "Applications"),
                            ("assets", "Assets"),
                            ("suppliers", "Suppliers"),
                            ("third_parties", "Third Parties"),
                            ("interested_parties", "Interested Parties"),
                            ("regulatory_requirements", "Regulatory Requirements"),
                            ("contractual_requirements", "Contractual Requirements"),
                            ("existing_policies", "Existing Policies"),
                            ("risks", "Risks"),
                            ("controls", "Controls"),
                        ],
                        max_length=40,
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                ("value", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("verified", "Verified"),
                            ("ai_inference", "AI Inference"),
                            ("missing", "Missing"),
                        ],
                        default="missing",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Organisation Interview, Information Request, Manual Entry",
                        max_length=200,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.organisation",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="knowledge_items_verified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["category", "label"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "category", "label"),
                        name="unique_knowledge_item_per_org",
                    )
                ],
            },
        ),
    ]
