# Generated by Django 5.2.16 on 2026-07-23 15:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        ("frameworks", "0001_initial"),
        ("risks", "0001_initial"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Control",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference_code",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "implementation_status",
                    models.CharField(
                        choices=[
                            ("not_implemented", "Not Implemented"),
                            ("partially_implemented", "Partially Implemented"),
                            ("implemented", "Implemented"),
                            ("not_applicable", "Not Applicable"),
                        ],
                        default="not_implemented",
                        max_length=30,
                    ),
                ),
                (
                    "effectiveness",
                    models.CharField(
                        choices=[
                            ("not_tested", "Not Tested"),
                            ("not_effective", "Not Effective"),
                            ("partially_effective", "Partially Effective"),
                            ("effective", "Effective"),
                        ],
                        default="not_tested",
                        max_length=30,
                    ),
                ),
                ("implementation_notes", models.TextField(blank=True)),
                (
                    "framework_requirements",
                    models.ManyToManyField(
                        blank=True, related_name="controls", to="frameworks.requirement"
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.organisation",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="controls_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "policies",
                    models.ManyToManyField(
                        blank=True, related_name="controls", to="documents.document"
                    ),
                ),
                (
                    "risks",
                    models.ManyToManyField(
                        blank=True, related_name="controls", to="risks.risk"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ControlTest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("test_date", models.DateField()),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("partial", "Partial"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "control",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tests",
                        to="controls.control",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.organisation",
                    ),
                ),
                (
                    "tested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-test_date"],
            },
        ),
        migrations.CreateModel(
            name="SoAEntry",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("applicable", models.BooleanField(default=True)),
                ("justification", models.TextField(blank=True)),
                (
                    "control",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soa_entries",
                        to="controls.control",
                    ),
                ),
                (
                    "framework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soa_entries",
                        to="frameworks.framework",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["control__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "framework", "control"),
                        name="unique_soa_entry",
                    )
                ],
            },
        ),
    ]
