# Generated by Django 5.2.16 on 2026-07-23 15:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("controls", "0001_initial"),
        ("risks", "0001_initial"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference_code",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("information", "Information Asset"),
                            ("system", "System"),
                            ("application", "Application"),
                            ("hardware", "Hardware"),
                            ("data_repository", "Data Repository"),
                        ],
                        default="information",
                        max_length=20,
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("internal", "Internal"),
                            ("confidential", "Confidential"),
                            ("restricted", "Restricted"),
                        ],
                        default="internal",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("related_process", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("planned", "Planned"),
                            ("retired", "Retired"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.organisation",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_controls",
                    models.ManyToManyField(
                        blank=True, related_name="assets", to="controls.control"
                    ),
                ),
                (
                    "related_risks",
                    models.ManyToManyField(
                        blank=True, related_name="assets", to="risks.risk"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
