# Generated by Django 5.2.16 on 2026-07-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0001_initial"),
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="related_suppliers",
            field=models.ManyToManyField(
                blank=True, related_name="assets", to="suppliers.supplier"
            ),
        ),
    ]
