# Generated by Django 5.2.16 on 2026-07-23 15:33

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frameworks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="frameworkimport",
            name="source_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="framework_imports/",
                validators=[core.validators.validate_upload_file],
            ),
        ),
    ]
