# Generated by Django 5.2.16 on 2026-07-23 17:37

import core.validators
import frameworks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frameworks", "0002_alter_frameworkimport_source_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="frameworkimport",
            name="source_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=frameworks.models.framework_import_upload_path,
                validators=[core.validators.validate_upload_file],
            ),
        ),
    ]
