# Generated by Django 5.2.16 on 2026-07-24 13:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frameworks", "0003_alter_frameworkimport_source_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="FrameworkCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(max_length=60, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.CharField(blank=True, max_length=300)),
                ("order", models.PositiveIntegerField(default=100)),
            ],
            options={
                "verbose_name_plural": "Framework categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="framework",
            name="icon",
            field=models.CharField(
                blank=True,
                default="framework",
                help_text="Icon key from core.templatetags.icons — see the icon set there.",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="framework",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("draft", "Draft"),
                    ("retired", "Retired"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="framework",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="frameworks",
                to="frameworks.frameworkcategory",
            ),
        ),
    ]
