# Generated by Django 5.2.16 on 2026-07-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "frameworks",
            "0004_frameworkcategory_framework_icon_framework_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="code",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="framework",
            name="code",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="framework",
            name="icon",
            field=models.CharField(
                blank=True,
                default="framework",
                help_text="Icon key from core.templatetags.icons — see the icon set there.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="framework",
            name="version",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="ref_code",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
