# Generated by Django 5.2.16 on 2026-07-23 15:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("frameworks", "0001_initial"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Risk",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference_code",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                ("title", models.CharField(max_length=250)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("information_security", "Information Security"),
                            ("operational", "Operational"),
                            ("financial", "Financial"),
                            ("compliance", "Compliance / Regulatory"),
                            ("strategic", "Strategic"),
                            ("reputational", "Reputational"),
                            ("third_party", "Third Party / Supplier"),
                            ("people", "People"),
                            ("other", "Other"),
                        ],
                        default="information_security",
                        max_length=30,
                    ),
                ),
                (
                    "asset_process",
                    models.CharField(
                        blank=True,
                        help_text="Affected asset or business process",
                        max_length=250,
                    ),
                ),
                ("threat", models.CharField(blank=True, max_length=300)),
                ("vulnerability", models.CharField(blank=True, max_length=300)),
                (
                    "likelihood",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=3,
                    ),
                ),
                (
                    "impact",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=3,
                    ),
                ),
                (
                    "inherent_risk_score",
                    models.PositiveSmallIntegerField(default=9, editable=False),
                ),
                ("existing_controls", models.TextField(blank=True)),
                (
                    "residual_likelihood",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        null=True,
                    ),
                ),
                (
                    "residual_impact",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        null=True,
                    ),
                ),
                (
                    "residual_risk_score",
                    models.PositiveSmallIntegerField(
                        blank=True, editable=False, null=True
                    ),
                ),
                (
                    "treatment",
                    models.CharField(
                        choices=[
                            ("avoid", "Avoid"),
                            ("mitigate", "Mitigate"),
                            ("transfer", "Transfer"),
                            ("accept", "Accept"),
                        ],
                        default="mitigate",
                        max_length=20,
                    ),
                ),
                ("treatment_plan", models.TextField(blank=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_treatment", "In Treatment"),
                            ("accepted", "Accepted"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.organisation",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="risks_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_requirements",
                    models.ManyToManyField(
                        blank=True, related_name="risks", to="frameworks.requirement"
                    ),
                ),
                (
                    "treatment_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="risk_treatments_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-inherent_risk_score"],
            },
        ),
        migrations.CreateModel(
            name="RiskMatrixConfig",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("very_low_max", models.PositiveSmallIntegerField(default=4)),
                ("low_max", models.PositiveSmallIntegerField(default=9)),
                ("medium_max", models.PositiveSmallIntegerField(default=15)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.organisation",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation",), name="unique_risk_matrix_per_org"
                    )
                ],
            },
        ),
    ]
