# Generated by Django 5.2.16 on 2026-07-23 14:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organisation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                (
                    "organisation_type",
                    models.CharField(
                        choices=[
                            ("sme", "Small / Medium Enterprise"),
                            ("npo", "Non-Profit Organisation"),
                            ("ngo", "Non-Governmental Organisation"),
                            ("sdp", "Skills Development Provider"),
                            ("public_sector", "Public Sector Entity"),
                            ("consultancy", "Consultancy / Practitioner"),
                            ("other", "Other"),
                        ],
                        default="sme",
                        max_length=20,
                    ),
                ),
                ("industry", models.CharField(blank=True, max_length=150)),
                ("registration_number", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(default="South Africa", max_length=100)),
                ("province", models.CharField(blank=True, max_length=100)),
                ("website", models.URLField(blank=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="org_logos/"),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("1-10", "1–10 employees"),
                            ("11-50", "11–50 employees"),
                            ("51-200", "51–200 employees"),
                            ("201-500", "201–500 employees"),
                            ("500+", "500+ employees"),
                        ],
                        default="1-10",
                        max_length=30,
                    ),
                ),
                (
                    "is_demo",
                    models.BooleanField(
                        default=False,
                        help_text="Marks fictional demonstration tenants (e.g. NIBS).",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organisations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OrganisationInvite",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("consultant", "Consultant"),
                            ("org_admin", "Organisation Administrator"),
                            ("executive", "Executive / Approver"),
                            ("compliance_manager", "Compliance Manager"),
                            ("isms_manager", "ISMS Manager"),
                            ("control_owner", "Control Owner"),
                            ("risk_owner", "Risk Owner"),
                            ("document_owner", "Document Owner"),
                            ("internal_auditor", "Internal Auditor"),
                            ("contributor", "Contributor"),
                            ("external_reviewer", "External Reviewer"),
                            ("read_only", "Read-Only User"),
                        ],
                        default="contributor",
                        max_length=30,
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("accepted", models.BooleanField(default=False)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="tenancy.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("consultant", "Consultant"),
                            ("org_admin", "Organisation Administrator"),
                            ("executive", "Executive / Approver"),
                            ("compliance_manager", "Compliance Manager"),
                            ("isms_manager", "ISMS Manager"),
                            ("control_owner", "Control Owner"),
                            ("risk_owner", "Risk Owner"),
                            ("document_owner", "Document Owner"),
                            ("internal_auditor", "Internal Auditor"),
                            ("contributor", "Contributor"),
                            ("external_reviewer", "External Reviewer"),
                            ("read_only", "Read-Only User"),
                        ],
                        default="contributor",
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="memberships_invited",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="tenancy.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["organisation__name"],
                "unique_together": {("organisation", "user")},
            },
        ),
    ]
