# Generated by Django 5.2.16 on 2026-07-23 17:37

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="org_logos/",
                validators=[core.validators.validate_upload_file],
            ),
        ),
    ]
