# Generated by Django 5.2.16 on 2026-07-23 15:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("frameworks", "0001_initial"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewSession",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.organisation",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InterviewExchange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("question_text", models.CharField(max_length=500)),
                ("knowledge_category", models.CharField(blank=True, max_length=40)),
                ("knowledge_label", models.CharField(blank=True, max_length=200)),
                ("answer_text", models.TextField(blank=True)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchanges",
                        to="journeys.interviewsession",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="JourneyStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("plan", "Plan"),
                            ("do", "Do"),
                            ("check", "Check"),
                            ("act", "Act"),
                        ],
                        default="plan",
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "stage_title",
                    models.CharField(
                        blank=True,
                        help_text="Groups steps for the implementation stepper (e.g. 'Context of the Organisation'). Falls back to the linked requirement's domain title if blank.",
                        max_length=100,
                    ),
                ),
                ("stage_order", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "guidance_what",
                    models.TextField(blank=True, verbose_name="What is required?"),
                ),
                (
                    "guidance_why",
                    models.TextField(blank=True, verbose_name="Why is it required?"),
                ),
                (
                    "guidance_who",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name="Who should be involved?",
                    ),
                ),
                (
                    "guidance_questions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="What questions should I ask?",
                    ),
                ),
                (
                    "guidance_existing_docs",
                    models.TextField(
                        blank=True, verbose_name="What documents might already exist?"
                    ),
                ),
                (
                    "guidance_evidence",
                    models.TextField(
                        blank=True, verbose_name="What evidence should I look for?"
                    ),
                ),
                ("completion_criteria", models.TextField(blank=True)),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("info", "Information / Acknowledgement"),
                            ("interview", "AI Guided Interview"),
                            ("document", "Produces a Controlled Document"),
                            ("risk_assessment", "Risk Assessment"),
                            ("controls", "Control Selection / SoA"),
                            ("evidence", "Evidence Collection"),
                            ("audit", "Internal Audit"),
                            ("management_review", "Management Review"),
                            ("corrective_actions", "Corrective Actions"),
                            ("audit_readiness", "Audit Readiness"),
                        ],
                        default="info",
                        max_length=30,
                    ),
                ),
                ("produces_document_type", models.CharField(blank=True, max_length=40)),
                ("requires_approval", models.BooleanField(default=False)),
                (
                    "requirement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journey_steps",
                        to="frameworks.requirement",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="step",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interview_sessions",
                to="journeys.journeystep",
            ),
        ),
        migrations.CreateModel(
            name="InformationRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "assigned_role_label",
                    models.CharField(
                        blank=True,
                        help_text="e.g. CEO, IT Manager, Information Officer",
                        max_length=100,
                    ),
                ),
                (
                    "assigned_email",
                    models.EmailField(
                        blank=True,
                        help_text="Used when the recipient is external / has no platform account.",
                        max_length=254,
                    ),
                ),
                ("question_text", models.TextField()),
                ("knowledge_category", models.CharField(blank=True, max_length=40)),
                ("knowledge_label", models.CharField(blank=True, max_length=200)),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("answered", "Answered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("response_text", models.TextField(blank=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="information_requests_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.organisation",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="information_requests_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="information_requests",
                        to="journeys.journeystep",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JourneyTemplate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            (
                                "build_from_scratch",
                                "Build a management system from scratch",
                            ),
                            ("gap_assessment", "Conduct a gap assessment"),
                            (
                                "improve_existing",
                                "Improve an existing management system",
                            ),
                            ("audit_prep", "Prepare for an internal audit"),
                            ("certification_prep", "Prepare for certification"),
                            ("popia_assessment", "Assess POPIA compliance"),
                            ("grc_baseline", "Conduct a GRC baseline assessment"),
                            ("implement_framework", "Implement a selected framework"),
                            ("import_custom_framework", "Import a custom framework"),
                        ],
                        max_length=40,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "framework",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journey_templates",
                        to="frameworks.framework",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="journeystep",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="journeys.journeytemplate",
            ),
        ),
        migrations.CreateModel(
            name="OrganisationJourney",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "current_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="journeys.journeystep",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.organisation",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organisation_journeys",
                        to="journeys.journeytemplate",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StepProgress",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation_journey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_progress",
                        to="journeys.organisationjourney",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_entries",
                        to="journeys.journeystep",
                    ),
                ),
            ],
            options={
                "ordering": ["step__order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation_journey", "step"),
                        name="unique_progress_per_step",
                    )
                ],
            },
        ),
    ]
