# Generated by Django 5.2.16 on 2026-07-23 15:18

import django.db.models.deletion
import documents.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai", "0001_initial"),
        ("frameworks", "0001_initial"),
        ("journeys", "0001_initial"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference_code",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                ("title", models.CharField(max_length=250)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("isms_scope", "ISMS Scope"),
                            (
                                "information_security_policy",
                                "Information Security Policy",
                            ),
                            ("risk_management_procedure", "Risk Management Procedure"),
                            ("access_control_policy", "Access Control Policy"),
                            (
                                "incident_management_procedure",
                                "Incident Management Procedure",
                            ),
                            ("supplier_security_policy", "Supplier Security Policy"),
                            ("popia_policy", "POPIA / Data Protection Policy"),
                            ("policy", "Policy"),
                            ("procedure", "Procedure"),
                            ("register", "Register Document"),
                            ("form", "Form / Template"),
                            ("other", "Other"),
                        ],
                        default="policy",
                        max_length=40,
                    ),
                ),
                ("version_label", models.CharField(default="0.1", max_length=20)),
                ("content", models.TextField(blank=True)),
                ("approval_date", models.DateField(blank=True, null=True)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("next_review_date", models.DateField(blank=True, null=True)),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("internal", "Internal"),
                            ("confidential", "Confidential"),
                            ("restricted", "Restricted"),
                        ],
                        default="internal",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("under_review", "Under Review"),
                            ("awaiting_approval", "Awaiting Approval"),
                            ("approved", "Approved"),
                            ("published", "Published"),
                            ("superseded", "Superseded"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=documents.models.document_upload_path,
                    ),
                ),
                ("ai_generated", models.BooleanField(default=False)),
                (
                    "ai_generation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="ai.aigeneration",
                    ),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "journey_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="journeys.journeystep",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.organisation",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_frameworks",
                    models.ManyToManyField(
                        blank=True, related_name="documents", to="frameworks.framework"
                    ),
                ),
                (
                    "related_requirements",
                    models.ManyToManyField(
                        blank=True,
                        related_name="documents",
                        to="frameworks.requirement",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_label", models.CharField(max_length=20)),
                ("content", models.TextField(blank=True)),
                (
                    "status_at_snapshot",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("draft", "Draft"),
                            ("under_review", "Under Review"),
                            ("awaiting_approval", "Awaiting Approval"),
                            ("approved", "Approved"),
                            ("published", "Published"),
                            ("superseded", "Superseded"),
                            ("archived", "Archived"),
                        ],
                        max_length=20,
                    ),
                ),
                ("change_reason", models.CharField(blank=True, max_length=300)),
                ("document_hash", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
