# Generated by Django 5.2.16 on 2026-07-23 15:33

import core.validators
import django.db.models.deletion
import evidence.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("controls", "0001_initial"),
        ("frameworks", "0002_alter_frameworkimport_source_file"),
        ("risks", "0001_initial"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Evidence",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference_code",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "evidence_type",
                    models.CharField(
                        choices=[
                            ("document", "Document"),
                            ("screenshot", "Screenshot"),
                            ("log_export", "Log Export"),
                            ("record", "Record"),
                            ("sign_off", "Sign-off / Approval Record"),
                            ("other", "Other"),
                        ],
                        default="document",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=evidence.models.evidence_upload_path,
                        validators=[core.validators.validate_upload_file],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "validity_period_months",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("unverified", "Unverified"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="unverified",
                        max_length=20,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.organisation",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evidence_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_controls",
                    models.ManyToManyField(
                        blank=True, related_name="evidence_items", to="controls.control"
                    ),
                ),
                (
                    "related_requirements",
                    models.ManyToManyField(
                        blank=True,
                        related_name="evidence_items",
                        to="frameworks.requirement",
                    ),
                ),
                (
                    "related_risks",
                    models.ManyToManyField(
                        blank=True, related_name="evidence_items", to="risks.risk"
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evidence_uploaded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Evidence",
                "ordering": ["-created_at"],
            },
        ),
    ]
