# Generated by Django 5.2.16 on 2026-07-23 15:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("controls", "0001_initial"),
        ("risks", "0001_initial"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangeEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("new_employee", "New Employee"),
                            ("employee_departure", "Employee Departure"),
                            ("new_supplier", "New Supplier"),
                            ("new_system", "New System"),
                            ("new_office", "New Office"),
                            ("new_business_process", "New Business Process"),
                            ("policy_change", "Policy Change"),
                            ("security_incident", "Security Incident"),
                            ("data_breach", "Data Breach"),
                            ("regulatory_change", "Regulatory Change"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("reviewed", "Reviewed"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("review_notes", models.TextField(blank=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.organisation",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference_code",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                ("title", models.CharField(max_length=250)),
                ("description", models.TextField(help_text="What happened?")),
                (
                    "occurred_at",
                    models.DateTimeField(
                        blank=True, help_text="When did it happen?", null=True
                    ),
                ),
                (
                    "discovered_at",
                    models.DateTimeField(
                        blank=True, help_text="When was it discovered?", null=True
                    ),
                ),
                ("systems_affected", models.TextField(blank=True)),
                ("information_affected", models.TextField(blank=True)),
                ("personal_info_involved", models.BooleanField(default=False)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("immediate_actions", models.TextField(blank=True)),
                ("root_cause", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reported", "Reported"),
                            ("investigating", "Investigating"),
                            ("contained", "Contained"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="reported",
                        max_length=20,
                    ),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "discovered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents_discovered",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.organisation",
                    ),
                ),
                (
                    "related_controls",
                    models.ManyToManyField(
                        blank=True, related_name="incidents", to="controls.control"
                    ),
                ),
                (
                    "related_risks",
                    models.ManyToManyField(
                        blank=True, related_name="incidents", to="risks.risk"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
